# Generated by Django 6.0.4 on 2026-06-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('SNo', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Detail', models.TextField()),
                ('Github', models.CharField(max_length=200)),
                ('Project', models.CharField(max_length=200)),
            ],
        ),
    ]
